- name: Deploy a web application
  hosts: db_web_server1,db_web_server2
  user: sshuser
  become: yes
  tasks:
  - name: Install all required dependencies
    apt: 
      name: ['python3', 'python3-apt']
      state: present

  - name: Install all required dependencies
    apt: 
      name: ['python3-setuptools', 'python3-dev', 'build-essential', 'python3-pip', 'python3-mysqldb']
      state: present

  - name: Install and Configure Database
    apt: 
      name: ['mysql-server', 'mysql-client']
      state: present

  - name: Start Database Service
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Create Application Database
    mysql_db: name=employee_db state=present

  - name: Create Database User
    mysql_user:
      name: db_user
      password: Passw0rd
      priv: '*.*:ALL'
      host: '%'
      state: present

  - name: Install Python Flask dependency
    pip:
      name: ['flask', 'flask-mysql']
      state: present

  - name: Copy the python code
    copy: src=app.py dest=/opt/app.py

  - name: Start the web server
    shell: FLASK_APP=/opt/app.py flask run --host=0.0.0.0 &