- name: Deploy a web application
  hosts: db_web_server1,db_web_server2
  user: sshuser
  become: yes
  tasks:
  - name: Install Python
    apt: 
      name: ['python3', 'python3-apt']
      state: present

  - name: Install all required dependencies
    apt: 
      name: ['python3-setuptools', 'python3-dev', 'build-essential', 'python3-pip', 'python3-mysqldb']
      state: present

  - include: ./tasks/deploy_db.yml

  - include: ./tasks/deploy_web.yml
