---
# tasks file for python

- name: Install Python
  apt: 
    name: ['python3', 'python3-apt']
    state: present

- name: Install all required dependencies
  apt: 
    name: ['python3-setuptools', 'python3-dev', 'build-essential', 'python3-pip', 'python3-mysqldb']
    state: present